channels:
  - https://artifactory.capstoneco.com/artifactory/api/conda/conda
  - https://conda.capstoneco.com/pkgs/spokes/solutions/trunk/packages
dependencies:
  - msodbcsql17=17.10.1.1=capstone_hd758a8b
  - pep8=1.7.1
  - pymongo=4.3.2
  - numerix=19.1.1=capstone_py39
  - pyvolar=3.19.0
  - solutions-activation=2.0.0
  - tqdm=4.64.1
  - cvxopt=1.3.1
  - openpyxl=3.0.10
  - psycopg2=2.9.3
  - pytz-deprecation-shim=0.1.0.post0
  - pytz=2022.6
  - tzlocal=2.1
  - et-xmlfile=1.0.1
  - gitpython=3.1.31
  - mosek=9.3.22
  - snakeviz=2.2.0
  - sqlalchemy=1.4.36
  - cassandra-driver=3.28.0
  - paramiko=3.2.0
  - matplotlib=3.3.2
  - capdata
  - modin-dask=0.22.1
  - scipy=1.9.3
  - statsmodels=0.13.5
  - pip=23.1.2
  - numpy=1.25.2
  - pyarrow=10.0.1
  - pandas=1.5.3
  - plotly=5.4.0
  - requests=2.32.3
  - openssl=1.1.1t
  - boto3=1.24.28
  - schedule=1.2.0
  - pyctp_uat_deployed=7.63.1
  - datalake=2.1.7
  - pip:
    - pyodbc==4.0.39