df_curve_config = {
    'EUR': {
        "OIS": 'RATES.OIS.EUR_EONIA.PAR.1D,RATES.OIS.EUR_EONIA.PAR.1W,RATES.OIS.EUR_EONIA.PAR.2W,RATES.OIS.EUR_EONIA.PAR.3W,RATES.OIS.EUR_EONIA.PAR.1M,RATES.OIS.EUR_EONIA.PAR.2M,' +
               'RATES.OIS.EUR_EONIA.PAR.3M,RATES.OIS.EUR_EONIA.PAR.4M,RATES.OIS.EUR_EONIA.PAR.5M,RATES.OIS.EUR_EONIA.PAR.6M,RATES.OIS.EUR_EONIA.PAR.7M,RATES.OIS.EUR_EONIA.PAR.8M,RATES.OIS.EUR_EONIA.PAR.9M,' +
               'RATES.OIS.EUR_EONIA.PAR.10M,RATES.OIS.EUR_EONIA.PAR.11M,RATES.OIS.EUR_EONIA.PAR.1Y,RATES.OIS.EUR_EONIA.PAR.15M,RATES.OIS.EUR_EONIA.PAR.18M,RATES.OIS.EUR_EONIA.PAR.21M' +
               'RATES.OIS.EUR_EONIA.PAR.2Y,RATES.OIS.EUR_EONIA.PAR.3Y,RATES.OIS.EUR_EONIA.PAR.4Y,RATES.OIS.EUR_EONIA.PAR.5Y,RATES.OIS.EUR_EONIA.PAR.6Y,RATES.OIS.EUR_EONIA.PAR.7Y' +
               'RATES.OIS.EUR_EONIA.PAR.8Y,RATES.OIS.EUR_EONIA.PAR.9Y,RATES.OIS.EUR_EONIA.PAR.10Y,RATES.OIS.EUR_EONIA.PAR.12Y,RATES.OIS.EUR_EONIA.PAR.15Y,RATES.OIS.EUR_EONIA.PAR.20Y,' +
               'RATES.OIS.EUR_EONIA.PAR.30Y,RATES.OIS.EUR_EONIA.PAR.40Y,RATES.OIS.EUR_EONIA.PAR.50Y',
    },
    'JPY': {
        'OIS': 'RATES.OIS.JPY_TONAR.PAR.1D,RATES.OIS.JPY_TONAR.PAR.1W,RATES.OIS.JPY_TONAR.PAR.2W,RATES.OIS.JPY_TONAR.PAR.3W,RATES.OIS.JPY_TONAR.PAR.1M,RATES.OIS.JPY_TONAR.PAR.2M,' +
               'RATES.OIS.JPY_TONAR.PAR.3M,RATES.OIS.JPY_TONAR.PAR.4M,RATES.OIS.JPY_TONAR.PAR.5M,RATES.OIS.JPY_TONAR.PAR.6M,RATES.OIS.JPY_TONAR.PAR.7M,RATES.OIS.JPY_TONAR.PAR.8M,RATES.OIS.JPY_TONAR.PAR.9M,' +
               'RATES.OIS.JPY_TONAR.PAR.10M,RATES.OIS.JPY_TONAR.PAR.11M,RATES.OIS.JPY_TONAR.PAR.1Y,RATES.OIS.JPY_TONAR.PAR.15M,RATES.OIS.JPY_TONAR.PAR.18M,RATES.OIS.JPY_TONAR.PAR.21M,' +
               'RATES.OIS.JPY_TONAR.PAR.2Y,RATES.OIS.JPY_TONAR.PAR.3Y,RATES.OIS.JPY_TONAR.PAR.4Y,RATES.OIS.JPY_TONAR.PAR.5Y,RATES.OIS.JPY_TONAR.PAR.6Y,RATES.OIS.JPY_TONAR.PAR.7Y,' +
               'RATES.OIS.JPY_TONAR.PAR.8Y,RATES.OIS.JPY_TONAR.PAR.9Y,RATES.OIS.JPY_TONAR.PAR.10Y,RATES.OIS.JPY_TONAR.PAR.12Y,RATES.OIS.JPY_TONAR.PAR.15Y,RATES.OIS.JPY_TONAR.PAR.20Y,' +
               'RATES.OIS.JPY_TONAR.PAR.30Y,RATES.OIS.JPY_TONAR.PAR.40Y,RATES.OIS.JPY_TONAR.PAR.50Y'
    },
    'AUD': {
        "OIS": 'RATES.OIS.AUD_AONIA.PAR.1D,RATES.OIS.AUD_AONIA.PAR.1W,RATES.OIS.AUD_AONIA.PAR.2W,RATES.OIS.AUD_AONIA.PAR.3W,RATES.OIS.AUD_AONIA.PAR.1M,RATES.OIS.AUD_AONIA.PAR.2M,' +
               'RATES.OIS.AUD_AONIA.PAR.3M,RATES.OIS.AUD_AONIA.PAR.4M,RATES.OIS.AUD_AONIA.PAR.5M,RATES.OIS.AUD_AONIA.PAR.6M,RATES.OIS.AUD_AONIA.PAR.7M,RATES.OIS.AUD_AONIA.PAR.8M,RATES.OIS.AUD_AONIA.PAR.9M,' +
               'RATES.OIS.AUD_AONIA.PAR.10M,RATES.OIS.AUD_AONIA.PAR.11M,RATES.OIS.AUD_AONIA.PAR.1Y,RATES.OIS.AUD_AONIA.PAR.15M,RATES.OIS.AUD_AONIA.PAR.18M,RATES.OIS.AUD_AONIA.PAR.21M,' +
               'RATES.OIS.AUD_AONIA.PAR.2Y,RATES.OIS.AUD_AONIA.PAR.3Y,RATES.OIS.AUD_AONIA.PAR.4Y,RATES.OIS.AUD_AONIA.PAR.5Y,RATES.OIS.AUD_AONIA.PAR.6Y,RATES.OIS.AUD_AONIA.PAR.7Y,' +
               'RATES.OIS.AUD_AONIA.PAR.8Y,RATES.OIS.AUD_AONIA.PAR.9Y,RATES.OIS.AUD_AONIA.PAR.10Y,RATES.OIS.AUD_AONIA.PAR.12Y,RATES.OIS.AUD_AONIA.PAR.15Y,RATES.OIS.AUD_AONIA.PAR.20Y,' +
               'RATES.OIS.AUD_AONIA.PAR.30Y,RATES.OIS.AUD_AONIA.PAR.40Y,RATES.OIS.AUD_AONIA.PAR.50Y'
    },
    'GBP': {
        "OIS": 'RATES.OIS.GBP_SONIA.PAR.3M,' +
               'RATES.OIS.GBP_SONIA.PAR.1Y,' +
               'RATES.OIS.GBP_SONIA.PAR.2Y,RATES.OIS.GBP_SONIA.PAR.3Y,RATES.OIS.GBP_SONIA.PAR.4Y,RATES.OIS.GBP_SONIA.PAR.5Y,RATES.OIS.GBP_SONIA.PAR.6Y,RATES.OIS.GBP_SONIA.PAR.7Y,' +
               'RATES.OIS.GBP_SONIA.PAR.8Y,RATES.OIS.GBP_SONIA.PAR.9Y,RATES.OIS.GBP_SONIA.PAR.10Y,RATES.OIS.GBP_SONIA.PAR.12Y,RATES.OIS.GBP_SONIA.PAR.15Y,RATES.OIS.GBP_SONIA.PAR.20Y,' +
               'RATES.OIS.GBP_SONIA.PAR.30Y',
        "SWAP": 'RATES.SWAP_LIBOR.GBP.PAR.3M,' +
                'RATES.SWAP_LIBOR.GBP.PAR.1Y,' +
                'RATES.SWAP_LIBOR.GBP.PAR.2Y,RATES.SWAP_LIBOR.GBP.PAR.3Y,RATES.SWAP_LIBOR.GBP.PAR.4Y,RATES.SWAP_LIBOR.GBP.PAR.5Y,RATES.SWAP_LIBOR.GBP.PAR.6Y,RATES.SWAP_LIBOR.GBP.PAR.7Y,' +
                'RATES.SWAP_LIBOR.GBP.PAR.8Y,RATES.SWAP_LIBOR.GBP.PAR.9Y,RATES.SWAP_LIBOR.GBP.PAR.10Y,RATES.SWAP_LIBOR.GBP.PAR.12Y,RATES.SWAP_LIBOR.GBP.PAR.15Y,RATES.SWAP_LIBOR.GBP.PAR.20Y,' +
                'RATES.SWAP_LIBOR.GBP.PAR.30Y',
    },
    'USD': {
        "OIS": 'RATES.OIS.USD_SOFR.PAR.3M,' +
               'RATES.OIS.USD_SOFR.PAR.1Y,' +
               'RATES.OIS.USD_SOFR.PAR.2Y,RATES.OIS.USD_SOFR.PAR.3Y,RATES.OIS.USD_SOFR.PAR.4Y,RATES.OIS.USD_SOFR.PAR.5Y,RATES.OIS.USD_SOFR.PAR.6Y,RATES.OIS.USD_SOFR.PAR.7Y,' +
               'RATES.OIS.USD_SOFR.PAR.8Y,RATES.OIS.USD_SOFR.PAR.9Y,RATES.OIS.USD_SOFR.PAR.10Y,RATES.OIS.USD_SOFR.PAR.12Y,RATES.OIS.USD_SOFR.PAR.15Y,RATES.OIS.USD_SOFR.PAR.20Y,' +
               'RATES.OIS.USD_SOFR.PAR.30Y',
        "SWAP": 'RATES.SWAP_LIBOR.USD.PAR.1W,RATES.SWAP_LIBOR.USD.PAR.3M,' +
                'RATES.SWAP_LIBOR.USD.PAR.1Y,' +
                'RATES.SWAP_LIBOR.USD.PAR.2Y,RATES.SWAP_LIBOR.USD.PAR.3Y,RATES.SWAP_LIBOR.USD.PAR.4Y,RATES.SWAP_LIBOR.USD.PAR.5Y,RATES.SWAP_LIBOR.USD.PAR.6Y,RATES.SWAP_LIBOR.USD.PAR.7Y,' +
                'RATES.SWAP_LIBOR.USD.PAR.8Y,RATES.SWAP_LIBOR.USD.PAR.9Y,RATES.SWAP_LIBOR.USD.PAR.10Y,RATES.SWAP_LIBOR.USD.PAR.12Y,RATES.SWAP_LIBOR.USD.PAR.15Y,RATES.SWAP_LIBOR.USD.PAR.20Y,' +
                'RATES.SWAP_LIBOR.USD.PAR.30Y',
    },
}
