df_curve_config = {
    'EUR': {'source': 'CITI_VELOCITY',
            'curve_names': {"OIS", "OISSWAP", "SWAP"},
            'tickers': {
                "OIS": 'RATES.OIS.EUR_EONIA.PAR.1D,RATES.OIS.EUR_EONIA.PAR.1W,RATES.OIS.EUR_EONIA.PAR.2W,RATES.OIS.EUR_EONIA.PAR.3W,RATES.OIS.EUR_EONIA.PAR.1M,RATES.OIS.EUR_EONIA.PAR.2M,' +
                       'RATES.OIS.EUR_EONIA.PAR.3M,RATES.OIS.EUR_EONIA.PAR.4M,RATES.OIS.EUR_EONIA.PAR.5M,RATES.OIS.EUR_EONIA.PAR.6M,RATES.OIS.EUR_EONIA.PAR.7M,RATES.OIS.EUR_EONIA.PAR.8M,RATES.OIS.EUR_EONIA.PAR.9M,' +
                       'RATES.OIS.EUR_EONIA.PAR.10M,RATES.OIS.EUR_EONIA.PAR.11M,RATES.OIS.EUR_EONIA.PAR.1Y,RATES.OIS.EUR_EONIA.PAR.15M,RATES.OIS.EUR_EONIA.PAR.18M,RATES.OIS.EUR_EONIA.PAR.21M' +
                       'RATES.OIS.EUR_EONIA.PAR.2Y,RATES.OIS.EUR_EONIA.PAR.3Y,RATES.OIS.EUR_EONIA.PAR.4Y,RATES.OIS.EUR_EONIA.PAR.5Y,RATES.OIS.EUR_EONIA.PAR.6Y,RATES.OIS.EUR_EONIA.PAR.7Y' +
                       'RATES.OIS.EUR_EONIA.PAR.8Y,RATES.OIS.EUR_EONIA.PAR.9Y,RATES.OIS.EUR_EONIA.PAR.10Y,RATES.OIS.EUR_EONIA.PAR.12Y,RATES.OIS.EUR_EONIA.PAR.15Y,RATES.OIS.EUR_EONIA.PAR.20Y,' +
                       'RATES.OIS.EUR_EONIA.PAR.30Y,RATES.OIS.EUR_EONIA.PAR.40Y,RATES.OIS.EUR_EONIA.PAR.50Y',
                "OISSWAP": {
                    "3M": 'RATES.OIS.EUR_EUROSTR.FWD.1D.3M,RATES.OIS.EUR_EUROSTR.FWD.1W.3M,RATES.OIS.EUR_EUROSTR.FWD.2W.3M,RATES.OIS.EUR_EUROSTR.FWD.3W.3M,RATES.OIS.EUR_EUROSTR.FWD.1M.3M,RATES.OIS.EUR_EUROSTR.FWD.2M.3M,' 
                          'RATES.OIS.EUR_EUROSTR.FWD.3M.3M,RATES.OIS.EUR_EUROSTR.FWD.4M.3M,RATES.OIS.EUR_EUROSTR.FWD.5M.3M,RATES.OIS.EUR_EUROSTR.FWD.6M.3M,RATES.OIS.EUR_EUROSTR.FWD.7M.3M,RATES.OIS.EUR_EUROSTR.FWD.8M.3M,RATES.OIS.EUR_EUROSTR.FWD.9M.3M,' +
                          'RATES.OIS.EUR_EUROSTR.FWD.10M.3M,RATES.OIS.EUR_EUROSTR.FWD.11M.3M,RATES.OIS.EUR_EUROSTR.FWD.1Y.3M,RATES.OIS.EUR_EUROSTR.FWD.15M.3M,RATES.OIS.EUR_EUROSTR.FWD.18M.3M,RATES.OIS.EUR_EUROSTR.FWD.21M' +
                          'RATES.OIS.EUR_EUROSTR.FWD.2Y.3M,RATES.OIS.EUR_EUROSTR.FWD.3Y.3M,RATES.OIS.EUR_EUROSTR.FWD.4Y.3M,RATES.OIS.EUR_EUROSTR.FWD.5Y.3M,RATES.OIS.EUR_EUROSTR.FWD.6Y.3M,RATES.OIS.EUR_EUROSTR.FWD.7Y' +
                          'RATES.OIS.EUR_EUROSTR.FWD.8Y.3M,RATES.OIS.EUR_EUROSTR.FWD.9Y.3M,RATES.OIS.EUR_EUROSTR.FWD.10Y.3M,RATES.OIS.EUR_EUROSTR.FWD.12Y.3M,RATES.OIS.EUR_EUROSTR.FWD.15Y.3M,RATES.OIS.EUR_EUROSTR.FWD.20Y.3M,' +
                          'RATES.OIS.EUR_EUROSTR.FWD.30Y.3M,RATES.OIS.EUR_EUROSTR.FWD.40Y.3M,RATES.OIS.EUR_EUROSTR.FWD.50Y.3M',
                },
                "SWAP": {
                    "3M": 'RATES.SWAP_LIBOR.EUR.PAR.1W,RATES.SWAP_LIBOR.EUR.PAR.3M,RATES.SWAP_LIBOR.EUR.PAR.6M,RATES.SWAP_LIBOR.EUR.PAR.1Y,RATES.SWAP_LIBOR.EUR.PAR.2Y,RATES.SWAP_LIBOR.EUR.PAR.3Y,' +
                          'RATES.SWAP_LIBOR.EUR.PAR.4Y,RATES.SWAP_LIBOR.EUR.PAR.5Y,RATES.SWAP_LIBOR.EUR.PAR.6Y,RATES.SWAP_LIBOR.EUR.PAR.7Y,RATES.SWAP_LIBOR.EUR.PAR.8Y,RATES.SWAP_LIBOR.EUR.PAR.9Y,' +
                          'RATES.SWAP_LIBOR.EUR.PAR.10Y,RATES.SWAP_LIBOR.EUR.PAR.11Y,RATES.SWAP_LIBOR.EUR.PAR.12Y,RATES.SWAP_LIBOR.EUR.PAR.13Y,RATES.SWAP_LIBOR.EUR.PAR.14Y,RATES.SWAP_LIBOR.EUR.PAR.15Y,' +
                          'RATES.SWAP_LIBOR.EUR.PAR.16Y,RATES.SWAP_LIBOR.EUR.PAR.17Y,RATES.SWAP_LIBOR.EUR.PAR.18Y,RATES.SWAP_LIBOR.EUR.PAR.30Y,RATES.SWAP_LIBOR.EUR.PAR.40Y,RATES.SWAP_LIBOR.EUR.PAR.50Y'
                },
            },
            },
    'JPY': {'source': 'CITI_VELOCITY',
            'tickers': 'RATES.OIS.JPY_TONAR.PAR.1D,RATES.OIS.JPY_TONAR.PAR.1W,RATES.OIS.JPY_TONAR.PAR.2W,RATES.OIS.JPY_TONAR.PAR.3W,RATES.OIS.JPY_TONAR.PAR.1M,RATES.OIS.JPY_TONAR.PAR.2M,' +
                       'RATES.OIS.JPY_TONAR.PAR.3M,RATES.OIS.JPY_TONAR.PAR.4M,RATES.OIS.JPY_TONAR.PAR.5M,RATES.OIS.JPY_TONAR.PAR.6M,RATES.OIS.JPY_TONAR.PAR.7M,RATES.OIS.JPY_TONAR.PAR.8M,RATES.OIS.JPY_TONAR.PAR.9M,'+
                       'RATES.OIS.JPY_TONAR.PAR.10M,RATES.OIS.JPY_TONAR.PAR.11M,RATES.OIS.JPY_TONAR.PAR.1Y,RATES.OIS.JPY_TONAR.PAR.15M,RATES.OIS.JPY_TONAR.PAR.18M,RATES.OIS.JPY_TONAR.PAR.21M,' +
                       'RATES.OIS.JPY_TONAR.PAR.2Y,RATES.OIS.JPY_TONAR.PAR.3Y,RATES.OIS.JPY_TONAR.PAR.4Y,RATES.OIS.JPY_TONAR.PAR.5Y,RATES.OIS.JPY_TONAR.PAR.6Y,RATES.OIS.JPY_TONAR.PAR.7Y,'+
                       'RATES.OIS.JPY_TONAR.PAR.8Y,RATES.OIS.JPY_TONAR.PAR.9Y,RATES.OIS.JPY_TONAR.PAR.10Y,RATES.OIS.JPY_TONAR.PAR.12Y,RATES.OIS.JPY_TONAR.PAR.15Y,RATES.OIS.JPY_TONAR.PAR.20Y,' +
                       'RATES.OIS.JPY_TONAR.PAR.30Y,RATES.OIS.JPY_TONAR.PAR.40Y,RATES.OIS.JPY_TONAR.PAR.50Y'},
    'AUD': {"source": "CITI_VELOCITY",
            "tickers": 'RATES.OIS.AUD_AONIA.PAR.1D,RATES.OIS.AUD_AONIA.PAR.1W,RATES.OIS.AUD_AONIA.PAR.2W,RATES.OIS.AUD_AONIA.PAR.3W,RATES.OIS.AUD_AONIA.PAR.1M,RATES.OIS.AUD_AONIA.PAR.2M,' +
                       'RATES.OIS.AUD_AONIA.PAR.3M,RATES.OIS.AUD_AONIA.PAR.4M,RATES.OIS.AUD_AONIA.PAR.5M,RATES.OIS.AUD_AONIA.PAR.6M,RATES.OIS.AUD_AONIA.PAR.7M,RATES.OIS.AUD_AONIA.PAR.8M,RATES.OIS.AUD_AONIA.PAR.9M,'+
                       'RATES.OIS.AUD_AONIA.PAR.10M,RATES.OIS.AUD_AONIA.PAR.11M,RATES.OIS.AUD_AONIA.PAR.1Y,RATES.OIS.AUD_AONIA.PAR.15M,RATES.OIS.AUD_AONIA.PAR.18M,RATES.OIS.AUD_AONIA.PAR.21M,' +
                       'RATES.OIS.AUD_AONIA.PAR.2Y,RATES.OIS.AUD_AONIA.PAR.3Y,RATES.OIS.AUD_AONIA.PAR.4Y,RATES.OIS.AUD_AONIA.PAR.5Y,RATES.OIS.AUD_AONIA.PAR.6Y,RATES.OIS.AUD_AONIA.PAR.7Y,'+
                       'RATES.OIS.AUD_AONIA.PAR.8Y,RATES.OIS.AUD_AONIA.PAR.9Y,RATES.OIS.AUD_AONIA.PAR.10Y,RATES.OIS.AUD_AONIA.PAR.12Y,RATES.OIS.AUD_AONIA.PAR.15Y,RATES.OIS.AUD_AONIA.PAR.20Y,' +
                       'RATES.OIS.AUD_AONIA.PAR.30Y,RATES.OIS.AUD_AONIA.PAR.40Y,RATES.OIS.AUD_AONIA.PAR.50Y'},
    'CAD': {'source': 'JPM_DATAQUERY',
             'tickers' :
             'MTE_cad/ois/0d/01D/rate,MTE_cad/ois/0d/01W/rate,MTE_cad/ois/0d/02W/rate,MTE_cad/ois/0d/01M/rate,MTE_cad/ois/0d/02M/rate,MTE_cad/ois/0d/03M/rate,'+
             'MTE_cad/ois/0d/04M/rate,MTE_cad/ois/0d/05M/rate,MTE_cad/ois/0d/06M/rate,MTE_cad/ois/0d/07M/rate,MTE_cad/ois/0d/08M/rate,MTE_cad/ois/0d/09M/rate,'+
             'MTE_cad/ois/0d/01Y/rate,MTE_cad/ois/0d/02Y/rate,MTE_cad/ois/0d/03Y/rate,MTE_cad/ois/0d/04Y/rate,MTE_cad/ois/0d/05Y/rate,MTE_cad/ois/0d/06Y/rate,'+
             'MTE_cad/ois/0d/07Y/rate,MTE_cad/ois/0d/08Y/rate,MTE_cad/ois/0d/09Y/rate,MTE_cad/ois/0d/10Y/rate',
             'pattern_override': r'MTE_cad/ois/0d/(\d{2})(Y|M|W|D)/rate' },
    'CHF': { 'source': 'JPM_DATAQUERY',
             'tickers' :
             'MTE_chf/ois/0d/01D/rate,MTE_chf/ois/0d/01W/rate,MTE_chf/ois/0d/02W/rate,MTE_chf/ois/0d/01M/rate,MTE_chf/ois/0d/02M/rate,MTE_chf/ois/0d/03M/rate,' +
             'MTE_chf/ois/0d/04M/rate,MTE_chf/ois/0d/05M/rate,MTE_chf/ois/0d/06M/rate,MTE_chf/ois/0d/07M/rate,MTE_chf/ois/0d/08M/rate,MTE_chf/ois/0d/09M/rate,' +
             'MTE_chf/ois/0d/01Y/rate,MTE_chf/ois/0d/02Y/rate,MTE_chf/ois/0d/03Y/rate,MTE_chf/ois/0d/04Y/rate,MTE_chf/ois/0d/05Y/rate,MTE_chf/ois/0d/06Y/rate,' +
             'MTE_chf/ois/0d/07Y/rate,MTE_chf/ois/0d/08Y/rate,MTE_chf/ois/0d/09Y/rate,MTE_chf/ois/0d/10Y/rate',
             'pattern_override': r'MTE_chf/ois/0d/(\d{2})(Y|M|W|D)/rate' },
    }

